spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: http://47.115.43.128:8848
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
server:
  port: 20000
  servlet:
    session:
      timeout: 30m
